cache_path: ./cache
checkpoint_symlink: "./models/symlinked/50_models.pkl"
data:
    dataset:
        from_h5:
            eval_splits:
                - val
            keys_order:
                - embed
                - label
            max_chunk: 1281167
            num_classes: 1000
            path:
                train: /mnt/qb/work/oh/arubinstein17/cache/ImageNet1k/train_cache/ed4f10f4ddeb07f1d876_torch_load_block_-1_model_imagenet1k_dataset_4_epochs_1281167_samples.hdf5
                val: /mnt/qb/work/oh/arubinstein17/cache/ImageNet1k/val_cache/ed4f10f4ddeb07f1d876_torch_load_block_-1_model_imagenet1k_dataset_1_epochs_50000_samples.hdf5
            total_samples:
                train: 5124668
        type: from_h5
        use_train_for_eval: false
        waterbirds:
            fraction: 1
            keep_metadata: false
            root_dir: /mnt/lustre/work/oh/arubinstein17/github/diverse-universe/tmp/DisEnsembler/<p>
    num_data_readers: 0
    unlabeled_dataset: null
# logging:
#     use_tb: false
#     use_wandb: false
#     wandb:
#         netrc_path: /home/oh/arubinstein17/.netrc
#         stats:
#             input: false
#             logits: false
#             loss: true
#             metrics: true
#             prediction: false
#             target: false
#         wandb_init_kwargs:
#             tags:
#                 - budget_train
#     output_csv:
#         path: /home/oh/arubinstein17/github/frozen-diverse-universe/experiments/Ultimate2604/2024-05-21_19:46:59.187320---fd723661c4d0f03bffad---217009/local_copy_Ultimate2604.csv
#         row_number: 530
#         spreadsheet_url: https://docs.google.com/spreadsheets/d/1AlsmgL6JmD0xkt7kYzwosF4XQ4XceB2zF4xv23f81IA/edit
#         worksheet_name: Ultimate2604
#     gdrive_storage_folder: https://drive.google.com/drive/folders/1bCKbgY29CXsgYSwBHk49weolkA5cBePT?usp=share_link
model:
    redneck_ensemble:
        base_estimator:
            resnet50:
                n_channels: 3
                n_classes: 2
                pretrained: true
            separation_config:
                block_id: -1
                separate: classifier
            torch_load:
                model_name: deit3_21k
                path: null
            type: torch_load
        keep_inactive_on_cpu: true
        n_models: 50
        random_select: 2
    type: redneck_ensemble
params:
    eval:
        batch_size: 32
        eval_only_last_epoch: false
    metric:
        accuracy_top_k:
            top_k: 1
        type: accuracy_top_k
    random_seed: 42
    setup: default
    to_eval: true
    to_profile: false
    to_train: true
    train:
        batch_size: 16
        criterion:
            divdis:
                disagree_after_epoch: 0
                disagree_below_threshold: null
                lambda: 0.5
                loss_type: a2d
                manual_lambda: 0.0002
                modifier: budget
                task_loss:
                    type: xce
                use_always_labeled: false
            type: divdis
        freeze_model_on_first_epoch: true
        n_epochs: 11
        optimizer:
            adam:
                weight_decay: 0.9
            nan_checking: true
            sgd:
                momentum: 0.9
                weight_decay: 0.0001
            start_lr: 0.001
            type: sgd
        reset_epochs: true
    use_gpu: true
patch:
    diversity_lambda: 0.5
statistics:
    batchwise: false
    keep_modelwise: false
    use_tb: false
    use_wandb: false
    wandb:
        netrc_path: /home/oh/arubinstein17/.netrc
        stats:
            input: false
            logits: false
            loss: true
            metrics: true
            prediction: false
            target: false
        wandb_init_kwargs:
            tags:
                - budget_train
use_hardcoded_config: false
